name: Build and Upload Docker Image

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Docker registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}  # Use the GITHUB_TOKEN for authentication

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .  # Docker build context (where the Dockerfile is located)
          file: ./Dockerfile  # Path to the Dockerfile (adjust if necessary)
          push: true  # Push the image to the registry
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest  # Tag the image with the repo name

      # Optionally, you can push additional tags
      - name: Tag and Push Docker Image with Version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF##*/}
          docker tag ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${VERSION}
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${VERSION}
