name: Deploy to GitHub Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job to run Python script and generate content
  generate-content:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Building Image
        run: docker build -t bot .
      
      - name: Running Container
        run: docker run --name GenBot -v "$(pwd)/generated_pages:/app/generated_pages" bot  
      
      - name: Cache Generated Pages
        uses: actions/cache@v3
        with:
          path: generated_pages
          key: ${{ runner.os }}-generated-pages-${{ github.run_id }}

  # Job to deploy to GitHub Pages
  deploy-to-pages:
    needs: generate-content
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Cached Generated Pages
        uses: actions/cache@v3
        with:
          path: generated_pages
          key: ${{ runner.os }}-generated-pages-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-generated-pages-

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: generated_pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
